from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('loan_inquiry/<str:loan_type>/', views.loan_inquiry, name='loan_inquiry'),
    path('terms-condition/', views.terms_condition, name='terms_condition'),
    path('perjanjian-ketentuan/', views.perjanjian, name='perjanjian'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('thank_you/', views.thank_you, name='thank_you'),
    path('history/', views.history, name='history'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('verify-otp-loan/', views.verify_otp_loan, name='verify_otp_loan'),
    path('inquiry-list/', views.inquiry_list, name='inquiry_list'),
    path('delete-inquiry/', views.delete_inquiry, name='delete_inquiry'),
    path('why-financialbroker/', views.why_us, name='why_us'),
    path('kpr/', views.kpr, name='kpr'),
    path('kpr/primary/', views.kpr_primary, name='kpr_primary'),
    path('kpr/secondary/', views.kpr_secondary, name='kpr_secondary'),
    path('kredit-investasi/', views.kredit_investasi, name='kredit_investasi'),
    path('multiguna-refinancing/', views.multiguna_refinancing, name='multiguna_refinancing'),
    path('multiguna/', views.multiguna, name='multiguna'),
    path('refinancing/', views.refinancing, name='refinancing'),
    path('modal-kerja/', views.modal_kerja, name='modal_kerja'),
    path('take-over/', views.take_over, name='take_over'),
    path('take-over/modal-kerja/', views.take_over_modal_kerja, name='take_over_modal_kerja'),
    path('take-over/multiguna/', views.take_over_multiguna, name='take_over_multiguna'),
    path('take-over/jual-beli/', views.take_over_jual_beli, name='take_over_jual_beli'),
    path('take-over/kpr/', views.take_over_kpr, name='take_over_kpr'),
    path('take-over/top-up/', views.take_over_kpr, name='take_over_top_up'),
    path('take-over/refinancing/', views.take_over_kpr, name='take_over_refinancing'),
    path('jaminan-bpkb-alat-berat/', views.jaminan_bpkb_alat_berat, name='jaminan_bpkb_alat_berat'),
    path('jaminan-bpkb/', views.jaminan_bpkb, name='jaminan_bpkb'),
    path('jaminan-alat-berat/', views.jaminan_alat_berat, name='jaminan_alat_berat'),
    path('invoice-po-spk-financing/', views.invoice_po_spk_financing, name='invoice_po_spk_financing'),
    path('po-financing/', views.po_financing, name='po_financing'),
    path('spk-financing/', views.spk_financing, name='spk_financing'),
    path('invoice-financing/', views.invoice_financing, name='invoice_financing'),
    path('bridging-offering-letter/', views.bridging_offering_letter, name='bridging_offering_letter'),
    path('sitemap.xml', views.sitemap, name='sitemap'),
    path('property_list', views.property_list, name='property_list'),
    path('property/<slug:slug>/', views.property_detail, name='property_detail'),
    path('add-property/', views.add_property, name='add_property'),
    path('admins/', views.custom_admin, name='custom_admin'),
    path('verify-admin/', views.admin_verification, name='admin_verification'),
    path('admins/property/delete/<int:pk>/admins/custom_admin', views.delete_property, name='delete_property'),
    path('property/<slug:slug>/', views.property_detail, name='property_detail'),
    path('property_inquiry/<int:property_id>', views.property_inquiry, name='property_inquiry'),
    path('verify-otp-property/', views.verify_otp_property, name='verify_otp_property'),
    path('ads-inquiry/', views.ads_inquiry, name='ads_inquiry'),
    path('verify-otp-ads/', views.verify_otp_ads, name='verify_otp_ads'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)