# Generated by Django 5.1 on 2025-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninquiry',
            name='loan_amount',
            field=models.CharField(max_length=100),
        ),
    ]
